---
- hosts: webservers
  remote_user: ubuntu
  tasks:
    - name: "Pull changes"
      ansible.builtin.git:
        repo: 'https://github.com/MadhavShroff/makeitaifor-me-server'
        dest: /home/ubuntu/makeitaifor-me-server
      become: yes

    - name: "Run redeploy script"
      ansible.builtin.command: '/bin/bash /home/ubuntu/makeitaifor-me-server/redeploy.sh'
      become: yes
